### PR TITLE
Added 'TEST' as target to run unit tests.

### PR DESCRIPTION
**Pull request by mikeller**

### CODE REVIEW

**Review by fujin — APPROVED** [review]
~I can't delete this~

**Comment by fujin** [comment]
Doesn't seem to work right, built locally:

```
docker run -e PLATFORM=test --rm -it -v $(pwd):/opt/betaflight betaflight/betaflight-build-tests:latest
make/targets.mk:163: *** Target 'test' is not valid, must be one of AFROMINI AIORACERF3 AIR32 AIRBOTF4 AIRBOTF4SD AIRHEROF3 ALIENFLIGHTF1 ALIENFLIGHTF3 ALIENFLIGHTF4 ALIENFLIGHTNGF7 ALIENWHOOPF4 ALIENWHOOPF7 ANYFCF7 ANYFCM7 BEEBRAIN BEEBRAIN_V2D BEEBRAIN_V2F BEEROTORF4 BETAFLIGHTF3 BETAFLIGHTF4 BLUEJAYF4 CC3D CC3D_OPBL CHEBUZZF3 CJMCU CLRACINGF4 CLRACINGF7 COLIBRI COLIBRI_OPBL COLIBRI_RACE CRAZYFLIE2 CRAZYFLIE2BQ DALRCF405 DOGE DYSF4PRO EACHIF3 ELLE0 EXUAVF4PRO F4BY FF_ACROWHOOPSP FF_FORTINIF4 FF_KOMBINI FF_PIKOBLX FF_PIKOF4 FF_PIKOF4OSD FF_RADIANCE FISHDRONEF4 FLIP32F3OSD FPVM_BETAFLIGHTF7 FRSKYF3 FRSKYF4 FURYF3 FURYF3OSD FURYF4 FURYF4OSD FURYF7 IMPULSERCF3 IRCFUSIONF3 ISHAPEDF3 KAKUTEF4 KAKUTEF4V2 KAKUTEF7 KISSCC KISSFC KISSFCV2F7 KIWIF4 KIWIF4V2 KROOZX LUMBAF3 LUXF4OSD LUXV2_RACE LUX_RACE MATEKF405 MATEKF411 MATEKF411RX MATEKF722 MICROSCISKY MIDELICF3 MLTEMPF4 MLTYPHF4 MOTOLAB MULTIFLITEPICO NAZE NERO NOX NUCLEOF446RE NUCLEOF7 NUCLEOF722 OMNIBUS OMNIBUSF4 OMNIBUSF4SD OMNIBUSF7 OMNIBUSF7V2 PLUMF4 PODIUMF4 PYRODRONEF4 RACEBASE RCEXPLORERF3 REVO REVOLT REVONANO REVO_OPBL RG_SSD_F3 RMDO SINGULARITY SIRINFPV SITL SOULF4 SPARKY SPARKY2 SPEKTRUMF400 SPRACINGF3 SPRACINGF3EVO SPRACINGF3MINI SPRACINGF3MQ SPRACINGF3NEO SPRACINGF3OSD SPRACINGF4EVO SPRACINGF4NEO STM32F3DISCOVERY TINYBEEF3 TINYFISH VRRACE WORMFC XRACERF4 X_RACERSPI YUPIF4 YUPIF7 ZCOREF3. Have you prepared a valid target.mk?.  Stop.
```

**Comment by fujin** [comment]
```
+ [ -z test ]
+ EXTRA_OPTIONS=
+ [ -n ]
+ EXTRA_OPTIONS=OPTIONS=
+ [ test = TEST ]
+ [ test = ALL ]
+ make ARM_SDK_DIR=/usr/ clean TARGET=test
make/targets.mk:163: *** Target 'test' is not valid, must be one of AFROMINI AIORACERF3 AIR32 AIRBOTF4 AIRBOTF4SD AIRHEROF3 ALIENFLIGHTF1 ALIENFLIGHTF3 ALIENFLIGHTF4 ALIENFLIGHTNGF7 ALIENWHOOPF4 ALIENWHOOPF7 ANYFCF7 ANYFCM7 BEEBRAIN BEEBRAIN_V2D BEEBRAIN_V2F BEEROTORF4 BETAFLIGHTF3 BETAFLIGHTF4 BLUEJAYF4 CC3D CC3D_OPBL CHEBUZZF3 CJMCU CLRACINGF4 CLRACINGF7 COLIBRI COLIBRI_OPBL COLIBRI_RACE CRAZYFLIE2 CRAZYFLIE2BQ DALRCF405 DOGE DYSF4PRO EACHIF3 ELLE0 EXUAVF4PRO F4BY FF_ACROWHOOPSP FF_FORTINIF4 FF_KOMBINI FF_PIKOBLX FF_PIKOF4 FF_PIKOF4OSD FF_RADIANCE FISHDRONEF4 FLIP32F3OSD FPVM_BETAFLIGHTF7 FRSKYF3 FRSKYF4 FURYF3 FURYF3OSD FURYF4 FURYF4OSD FURYF7 IMPULSERCF3 IRCFUSIONF3 ISHAPEDF3 KAKUTEF4 KAKUTEF4V2 KAKUTEF7 KISSCC KISSFC KISSFCV2F7 KIWIF4 KIWIF4V2 KROOZX LUMBAF3 LUXF4OSD LUXV2_RACE LUX_RACE MATEKF405 MATEKF411 MATEKF411RX MATEKF722 MICROSCISKY MIDELICF3 MLTEMPF4 MLTYPHF4 MOTOLAB MULTIFLITEPICO NAZE NERO NOX NUCLEOF446RE NUCLEOF7 NUCLEOF722 OMNIBUS OMNIBUSF4 OMNIBUSF4SD OMNIBUSF7 OMNIBUSF7V2 PLUMF4 PODIUMF4 PYRODRONEF4 RACEBASE RCEXPLORERF3 REVO REVOLT REVONANO REVO_OPBL RG_SSD_F3 RMDO SINGULARITY SIRINFPV SITL SOULF4 SPARKY SPARKY2 SPEKTRUMF400 SPRACINGF3 SPRACINGF3EVO SPRACINGF3MINI SPRACINGF3MQ SPRACINGF3NEO SPRACINGF3OSD SPRACINGF4EVO SPRACINGF4NEO STM32F3DISCOVERY TINYBEEF3 TINYFISH VRRACE WORMFC XRACERF4 X_RACERSPI YUPIF4 YUPIF7 ZCOREF3. Have you prepared a valid target.mk?.  Stop.
```

**Comment by fujin** [comment]
I'm dumb. Uppercase.

**Review by fujin — APPROVED** [review]
Tested OK.

Consider transforming ${PLATFORM} to upcase.

**Comment by mikeller** [comment]
Updated the parameter naming to better match the Betaflight Makefile.

**Pull request merged**
